import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs))
}


export const educationLevels = [
    { label: "O'rta ta'lim", key: 1 },
    { label: "O'rta maxsus ta'lim", key: 2 },
    { label: "Kasb-hunar ta'limi", key: 3 },
    { label: "Tugallanmagan oliy ta'lim", key: 4 },
    { label: "Oliy ta'lim", key: 5 },
    { label: "Magistratura", key: 6 },
];



 
export const dataTask: Column[] = [
    {
        id: "todo",
        name: "Qilish kerak",
        items: [
            {
                id: 1,
                title: "Login sahifasini yaratish",
                description: "Foydalanuvchi login qilishi uchun sahifa",
                priority: "Yuqori",
                deadline: "2025-07-01",
                responsible: "Javohir Karimov",
                subtasks: [
                    { id: 1, title: "Formani yaratish", completed: false },
                    { id: 2, title: "Validatsiya qo'shish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
                ],
                voiceNote: [],
            },
            {
                id: 2,
                title: "Ro'yxatdan o'tish sahifasi",
                description: "Yangi foydalanuvchilar uchun forma",
                priority: "O'rta",
                deadline: "2025-07-03",
                responsible: "Dilshod Abdullayev",
                subtasks: [
                    {
                        id: 3,
                        title: "Ism, email, parol maydonlari",
                        completed: false,
                    },
                ],
                images: [
                    "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
                ],
                voiceNote: [],
            },
            {
                id: 3,
                title: "Navbar component",
                description: "Sayt bo'ylab navigatsiya",
                priority: "Past",
                deadline: "2025-07-05",
                responsible: "Sevinch Tursunova",
                subtasks: [
                    { id: 4, title: "Linklar qo'shish", completed: false },
                    { id: 5, title: "Mobil versiya", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1537432376769-00aabc1b4f52",
                ],
                voiceNote: [],
            },
            {
                id: 4,
                title: "Footer yaratish",
                description: "Sayt pastki qismi",
                priority: "Past",
                deadline: "2025-07-06",
                responsible: "Kamola Yusupova",
                subtasks: [
                    { id: 6, title: "Bog'lanish info", completed: false },
                    { id: 7, title: "Ijtimoiy tarmoqlar", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1581090700227-1e8e3c40f75e",
                ],
                voiceNote: [],
            },
            {
                id: 5,
                title: "Ma'lumotlar bazasi ulash",
                description: "MongoDB ulash va sinash",
                priority: "Yuqori",
                deadline: "2025-07-07",
                responsible: "Azamat Sattorov",
                subtasks: [
                    { id: 8, title: "Connection sozlash", completed: false },
                    { id: 9, title: "Model yaratish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1581092160624-de7e1681f2fc",
                ],
                voiceNote: [],
            },
            {
                id: 6,
                title: "Redux Toolkit setup",
                description: "Global state management uchun",
                priority: "O'rta",
                deadline: "2025-07-08",
                responsible: "Murod Bekmurodov",
                subtasks: [
                    { id: 10, title: "Store yaratish", completed: false },
                    { id: 11, title: "Slice qo'shish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1611926653458-b9fdd8e3d7c2",
                ],
                voiceNote: [],
            },
            {
                id: 7,
                title: "Login API ulash",
                description: "Backend bilan integratsiya qilish",
                priority: "Yuqori",
                deadline: "2025-07-09",
                responsible: "Zarnigor Abdunazarova",
                subtasks: [
                    { id: 12, title: "Token saqlash", completed: false },
                    { id: 13, title: "Error handle qilish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1573164574394-df1e1a1f7ed6",
                ],
                voiceNote: [],
            },
            {
                id: 8,
                title: "Responsive dizayn",
                description: "Mobil va desktop mosligi",
                priority: "O'rta",
                deadline: "2025-07-10",
                responsible: "Shahzod Nasrullayev",
                subtasks: [
                    { id: 14, title: "Media queries", completed: false },
                    { id: 15, title: "Flex/Grid", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
                ],
                voiceNote: [],
            },
            {
                id: 9,
                title: "Dark mode qo'shish",
                description: "Foydalanuvchi tanlashi uchun",
                priority: "Past",
                deadline: "2025-07-11",
                responsible: "Madina Toshpulatova",
                subtasks: [
                    { id: 16, title: "Switch tugmasi", completed: false },
                    { id: 17, title: "Class qo'shish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d",
                ],
                voiceNote: [],
            },
            {
                id: 10,
                title: "Yuzlab test case yozish",
                description: "Har bir komponent uchun testlar",
                priority: "Yuqori",
                deadline: "2025-07-12",
                responsible: "Ismoil Raxmatov",
                subtasks: [
                    { id: 18, title: "Unit test", completed: false },
                    { id: 19, title: "Integration test", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1610564558314-2ad2b3063a9e",
                ],
                voiceNote: [],
            },
        ],
    },
    {
        id: "in-progress",
        name: "Qilinmoqda",
        items: [
            {
                id: 11,
                title: "Profil sahifasi",
                description: "Foydalanuvchi shaxsiy ma'lumotlari",
                priority: "O'rta",
                deadline: "2025-07-01",
                responsible: "Sanjar Qodirov",
                subtasks: [
                    { id: 20, title: "Ma'lumot ko'rsatish", completed: true },
                    { id: 21, title: "O'zgartirish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
                ],
                voiceNote: [],
            },
            {
                id: 12,
                title: "Postlar ro'yxatini chiqarish",
                description: "API orqali postlar",
                priority: "Yuqori",
                deadline: "2025-07-02",
                responsible: "Lola Rahmonova",
                subtasks: [
                    {
                        id: 22,
                        title: "Axios bilan ma'lumot olish",
                        completed: true,
                    },
                    { id: 23, title: "Loading UI", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
                ],
                voiceNote: [],
            },
            {
                id: 13,
                title: "Pagination qo'shish",
                description: "Postlarni sahifalash",
                priority: "Past",
                deadline: "2025-07-03",
                responsible: "Bekzod Mirzayev",
                subtasks: [
                    { id: 24, title: "Limit, page sozlash", completed: false },
                    { id: 25, title: "Buttons", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1586282022273-09c9c299b1f2",
                ],
                voiceNote: [],
            },
            {
                id: 14,
                title: "Filtrlash componenti",
                description: "Kategoriya va sana bo'yicha filtrlash",
                priority: "O'rta",
                deadline: "2025-07-04",
                responsible: "Nodira Alimova",
                subtasks: [
                    { id: 26, title: "Dropdown yaratish", completed: true },
                    { id: 27, title: "Query param", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1556742031-c6961e8560b0",
                ],
                voiceNote: [],
            },
            {
                id: 15,
                title: "Toast bildirishnomalar",
                description: "Success va error xabarlar",
                priority: "Past",
                deadline: "2025-07-05",
                responsible: "Olim Shukurov",
                subtasks: [
                    { id: 28, title: "Toast qo'shish", completed: true },
                    { id: 29, title: "Auto close qilish", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1624378440585-57b504d0e4a7",
                ],
                voiceNote: [],
            },
            {
                id: 16,
                title: "Parol tiklash sahifasi",
                description: "Parol unutganlar uchun sahifa",
                priority: "Yuqori",
                deadline: "2025-07-06",
                responsible: "Nodir Soliyev",
                subtasks: [
                    { id: 30, title: "Email yuborish", completed: false },
                    { id: 31, title: "Token bilan tiklash", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1573166364803-020b232b0031",
                ],
                voiceNote: [],
            },
            {
                id: 17,
                title: "Foydalanuvchi qo'shish formasi",
                description: "Admin panelda user qo'shish",
                priority: "O'rta",
                deadline: "2025-07-07",
                responsible: "Firuza Ergasheva",
                subtasks: [
                    { id: 32, title: "Form validation", completed: true },
                    { id: 33, title: "Role tanlash", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1556740749-887f6717d7e4",
                ],
                voiceNote: [],
            },
            {
                id: 18,
                title: "Loader animatsiyasi",
                description: "Ma'lumot yuklanayotganda animatsiya",
                priority: "Past",
                deadline: "2025-07-08",
                responsible: "Elyor Mamadaliyev",
                subtasks: [
                    { id: 34, title: "Spinner komponenti", completed: true },
                    { id: 35, title: "Shimmer effect", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1593642634367-d91a135587b5",
                ],
                voiceNote: [],
            },
            {
                id: 19,
                title: "Multi language qo'shish",
                description: "UZ / RU / EN tillari bilan ishlash",
                priority: "Yuqori",
                deadline: "2025-07-09",
                responsible: "Nozima Rustamova",
                subtasks: [
                    { id: 36, title: "i18n setup", completed: false },
                    { id: 37, title: "Tarjimani joylash", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1524648360130-8f3f5f0f2b66",
                ],
                voiceNote: [],
            },
            {
                id: 20,
                title: "Avatar upload qilish",
                description: "Foydalanuvchi rasm yuklashi uchun",
                priority: "O'rta",
                deadline: "2025-07-10",
                responsible: "Bahrom Valiyev",
                subtasks: [
                    { id: 38, title: "Input file", completed: true },
                    { id: 39, title: "Image preview", completed: false },
                ],
                images: [
                    "https://images.unsplash.com/photo-1618005198919-d3d4a1a39c4a",
                ],
                voiceNote: [],
            },
        ],
    },
    {
        id: "testing",
        name: "Test qilish",
        items: [
            {
                id: 21,
                title: "Unit testlar yozish",
                description: "Har bir komponent uchun test",
                priority: "Yuqori",
                deadline: "2025-07-11",
                responsible: "Bobur Islomov",
                subtasks: [
                    { id: 40, title: "Component test", completed: false },
                    { id: 41, title: "Hook test", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/men/45.jpg"],
                voiceNote: [],
            },
            {
                id: 22,
                title: "Form validation test",
                description: "Formalarning validatsiyasini test qilish",
                priority: "O'rta",
                deadline: "2025-07-12",
                responsible: "Ozoda Karimova",
                subtasks: [
                    { id: 42, title: "Email format", completed: false },
                    { id: 43, title: "Required fields", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/women/65.jpg"],
                voiceNote: [],
            },
            {
                id: 23,
                title: "Routing test",
                description: "To'g'ri sahifalarga yo'naltirilganini tekshirish",
                priority: "Past",
                deadline: "2025-07-13",
                responsible: "Rustam Sattorov",
                subtasks: [
                    { id: 44, title: "Home route", completed: false },
                    { id: 45, title: "404 sahifa", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/men/32.jpg"],
                voiceNote: [],
            },
            {
                id: 24,
                title: "Responsive test",
                description: "Mobil va desktop dizaynlar tekshiruvi",
                priority: "O'rta",
                deadline: "2025-07-14",
                responsible: "Dildora Umarova",
                subtasks: [
                    { id: 46, title: "Viewport sozlash", completed: false },
                    { id: 47, title: "Element joylashuvi", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/women/30.jpg"],
                voiceNote: [],
            },
            {
                id: 25,
                title: "Login testlari",
                description: "To'g'ri ma'lumot bilan kirish",
                priority: "Yuqori",
                deadline: "2025-07-15",
                responsible: "Sherzod Alimov",
                subtasks: [
                    { id: 48, title: "Success login", completed: false },
                    { id: 49, title: "Error message", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/men/55.jpg"],
                voiceNote: [],
            },
            {
                id: 26,
                title: "API testlari",
                description: "Ma'lumotlar to'g'ri kelayotganini tekshirish",
                priority: "O'rta",
                deadline: "2025-07-16",
                responsible: "Nargiza Nematova",
                subtasks: [
                    { id: 50, title: "GET test", completed: false },
                    { id: 51, title: "POST test", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/women/40.jpg"],
                voiceNote: [],
            },
            {
                id: 27,
                title: "Form reset test",
                description: "Forma qayta tozalanganda qiymatlar to'g'rimi",
                priority: "Past",
                deadline: "2025-07-17",
                responsible: "Qobil Ergashev",
                subtasks: [
                    { id: 52, title: "Reset button", completed: false },
                    { id: 53, title: "Default qiymat", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/men/22.jpg"],
                voiceNote: [],
            },
            {
                id: 28,
                title: "Toast test",
                description: "Bildirishnomalar chiqarilayotganini tekshirish",
                priority: "O'rta",
                deadline: "2025-07-18",
                responsible: "Mansur Raxmatov",
                subtasks: [
                    { id: 54, title: "Success toast", completed: false },
                    { id: 55, title: "Auto-close", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/men/70.jpg"],
                voiceNote: [],
            },
            {
                id: 29,
                title: "Pagination test",
                description: "Post sahifalanishini test qilish",
                priority: "Past",
                deadline: "2025-07-19",
                responsible: "Gulnoza Yuldasheva",
                subtasks: [
                    { id: 56, title: "Next page", completed: false },
                    { id: 57, title: "Previous page", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/women/75.jpg"],
                voiceNote: [],
            },
            {
                id: 30,
                title: "Performance test",
                description: "Ilovaning ishlash tezligini tekshirish",
                priority: "Yuqori",
                deadline: "2025-07-20",
                responsible: "Shahlo Toshpulatova",
                subtasks: [
                    { id: 58, title: "Load time", completed: false },
                    { id: 59, title: "Response time", completed: false },
                ],
                images: ["https://randomuser.me/api/portraits/women/24.jpg"],
                voiceNote: [],
            },
        ],
    },
    {
        id: "done",
        name: "Tugatildi",
        items: [
            {
                id: 31,
                title: "Proyekt yaratildi",
                description: "Initial setup va konfiguratsiya",
                priority: "Yuqori",
                deadline: "2025-06-01",
                responsible: "Asilbek Qodirov",
                subtasks: [
                    { id: 60, title: "Vite setup", completed: true },
                    { id: 61, title: "Git init", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/41.jpg"],
                voiceNote: [],
            },
            {
                id: 32,
                title: "Favicon o'rnatildi",
                description: "Brauzer uchun favicon qo'shildi",
                priority: "Past",
                deadline: "2025-06-02",
                responsible: "Adham Nurmatov",
                subtasks: [
                    { id: 62, title: "Icon tanlash", completed: true },
                    { id: 63, title: "HTML head", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/35.jpg"],
                voiceNote: [],
            },
            {
                id: 33,
                title: "Tailwind CSS qo'shildi",
                description: "Styling uchun Tailwind konfiguratsiyasi",
                priority: "Yuqori",
                deadline: "2025-06-03",
                responsible: "Salim Karimov",
                subtasks: [
                    { id: 64, title: "Tailwind install", completed: true },
                    { id: 65, title: "PostCSS sozlash", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/61.jpg"],
                voiceNote: [],
            },
            {
                id: 34,
                title: "Layout tayyorlandi",
                description: "Asosiy UI tuzilmasi",
                priority: "O'rta",
                deadline: "2025-06-04",
                responsible: "Dilrabo Aliyeva",
                subtasks: [
                    { id: 66, title: "Header", completed: true },
                    { id: 67, title: "Main", completed: true },
                    { id: 68, title: "Footer", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/women/28.jpg"],
                voiceNote: [],
            },
            {
                id: 35,
                title: "Navbar yakunlandi",
                description: "Navigatsiya tugmalari tayyor",
                priority: "Past",
                deadline: "2025-06-05",
                responsible: "Alisher Umarov",
                subtasks: [
                    { id: 69, title: "Logo qo'shish", completed: true },
                    { id: 70, title: "Linklar", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/52.jpg"],
                voiceNote: [],
            },
            {
                id: 36,
                title: "Footer yakunlandi",
                description: "Sayt pastki qismi dizayn jihatdan to'liq tayyor",
                priority: "Past",
                deadline: "2025-06-06",
                responsible: "Zuxra Qayumova",
                subtasks: [
                    { id: 71, title: "Kontakt info", completed: true },
                    { id: 72, title: "Ijtimoiy tarmoqlar", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/women/43.jpg"],
                voiceNote: [],
            },
            {
                id: 37,
                title: "Login sahifasi testdan o'tdi",
                description:
                    "Login sahifasi barcha qurilmalarda sinovdan o'tkazildi",
                priority: "Yuqori",
                deadline: "2025-06-07",
                responsible: "Anvar Jo'rayev",
                subtasks: [
                    { id: 73, title: "Mobil test", completed: true },
                    { id: 74, title: "Desktop test", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/19.jpg"],
                voiceNote: [],
            },
            {
                id: 38,
                title: "Ma'lumotlar bazasi backup qilindi",
                description: "Har kunlik avtomatik backup yo'lga qo'yildi",
                priority: "O'rta",
                deadline: "2025-06-08",
                responsible: "Lobar Toshmatova",
                subtasks: [
                    { id: 75, title: "Cron sozlash", completed: true },
                    { id: 76, title: "Test backup", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/women/52.jpg"],
                voiceNote: [],
            },
            {
                id: 39,
                title: "Responsive dizayn yakunlandi",
                description: "Barcha sahifalar responsiv ko'rinishda",
                priority: "Yuqori",
                deadline: "2025-06-09",
                responsible: "Shohruh Qodirov",
                subtasks: [
                    { id: 77, title: "Mobil layout", completed: true },
                    { id: 78, title: "Tablet layout", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/men/77.jpg"],
                voiceNote: [],
            },
            {
                id: 40,
                title: "Test yozuvlar tozalandi",
                description: "Fake va test maʼlumotlar DB dan o'chirildi",
                priority: "Past",
                deadline: "2025-06-10",
                responsible: "Dilnavoz Eshmatova",
                subtasks: [
                    { id: 79, title: "Postman test logs", completed: true },
                    { id: 80, title: "Seed data removal", completed: true },
                ],
                images: ["https://randomuser.me/api/portraits/women/69.jpg"],
                voiceNote: [],
            },
        ],
    },
]
