const USERS = "users/"
const HR = "hr/"
const LOCATION = "location/"

export const GET_ME = USERS + "admin-getme"
export const REFRESH_TOKEN = "refresh_token"
export const REGISTER = "register"
export const LOGIN = USERS + "login/admin"
export const COMPANIES = HR + 'companies'
export const MAP_POLYGONS = HR + 'map-statistics'
export const HR_API = 'users'
export const HR_ATTENDED = HR + "attended-users"
export const HR_ABSENTS = HR + "absent-users"
export const ALL_EMPLOYEES = HR + "all-employees"
export const POSITION = USERS + 'roles'
export const STATUS_COUNT = HR + 'status-count'
export const POSITION_PAYMENT = 'payments/paid-roles'
export const POSITION_USERS = 'payments/paid-users'
export const ENTRANCE_LOG = 'location/entrance-log'
export const OFFICE_DETAILS = HR + 'company-statistics'
export const ROLES_STATISTIC = HR + 'roles-statistics'
export const PAYMENTS_ROLES = 'payments/roles'
export const PAYMENTS = 'payments'
export const PAYMENTS_CANCELLED = 'payments/rollback'
export const USER_YEAR_TOTAL = HR + 'user-total-yearly-statistics'
export const USER_YEAR_TOTAL_MONTH = HR + 'user-yearly-statistics'
export const USER_YEAR_TOTAL_MONTH_DAYS = HR + 'user-monthly-statistics'
export const USER_YEAR_TOTAL_MONTH_DAYS_ONE = HR + 'user-daily-statistics'
export const USER_STATISTIC = HR + 'user-statistics-by-role'
export const PAYMENTS_ROLES_USERS = 'payments/users'
export const EXCUSE = HR + 'excuses'
export const EXCUSE_COUNT = HR + 'excuse-count'
export const ASSIGN_COMPANIES = USERS + 'assign_companies_to_user'
export const HR_EXCEL_TEMP = HR + 'sample-excel'
export const HR_EXCEL_DOWN = HR + 'excel-users'
export const HR_EXCEL_UP = HR + 'create-from-excel'
export const USER_LOCATIONS = LOCATION + 'users-locations'
export const ROTUES = LOCATION + 'routes'
export const PAYMENTS_USERS_MONTH = 'payments/billing-users'
export const PAYMENTS_USERS_MONTH_PRICE = 'payments/calculate-months'
export const FILTER = HR + 'filter/'
