/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainLandingImport } from './routes/_main/landing'
import { Route as MainHrCreateImport } from './routes/_main/hr-create'
import { Route as MainHrImport } from './routes/_main/hr'
import { Route as MainArrivalsImport } from './routes/_main/arrivals'
import { Route as MainAllEmployeesImport } from './routes/_main/all-employees'
import { Route as MainAbsentImport } from './routes/_main/absent'
import { Route as MainRolesIndexImport } from './routes/_main/roles/index'
import { Route as MainRequestsIndexImport } from './routes/_main/requests/index'
import { Route as MainProjectIndexImport } from './routes/_main/project/index'
import { Route as MainPlansIndexImport } from './routes/_main/plans/index'
import { Route as MainOfficeIndexImport } from './routes/_main/office/index'
import { Route as MainMapIndexImport } from './routes/_main/map/index'
import { Route as MainProjectIdImport } from './routes/_main/project/$id'
import { Route as MainPositionHrViewIdImport } from './routes/_main/position-hr-view/$id'
import { Route as MainPlansCheckoutImport } from './routes/_main/plans/checkout'
import { Route as MainOfficeCreateImport } from './routes/_main/office/create'
import { Route as MainOfficeIdImport } from './routes/_main/office/$id'
import { Route as MainOfficeEditIdImport } from './routes/_main/office-edit/$id'
import { Route as MainHrViewIdImport } from './routes/_main/hr-view/$id'

// Create Virtual Routes

const AuthAuthLazyImport = createFileRoute('/_auth/auth')()
const MainHrEditHrEditLazyImport = createFileRoute('/_main/hr-edit/$hr-edit')()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainLandingRoute = MainLandingImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => MainRoute,
} as any)

const MainHrCreateRoute = MainHrCreateImport.update({
  id: '/hr-create',
  path: '/hr-create',
  getParentRoute: () => MainRoute,
} as any)

const MainHrRoute = MainHrImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => MainRoute,
} as any)

const MainArrivalsRoute = MainArrivalsImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => MainRoute,
} as any)

const MainAllEmployeesRoute = MainAllEmployeesImport.update({
  id: '/all-employees',
  path: '/all-employees',
  getParentRoute: () => MainRoute,
} as any)

const MainAbsentRoute = MainAbsentImport.update({
  id: '/absent',
  path: '/absent',
  getParentRoute: () => MainRoute,
} as any)

const MainRolesIndexRoute = MainRolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => MainRoute,
} as any)

const MainRequestsIndexRoute = MainRequestsIndexImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => MainRoute,
} as any)

const MainProjectIndexRoute = MainProjectIndexImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => MainRoute,
} as any)

const MainPlansIndexRoute = MainPlansIndexImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeIndexRoute = MainOfficeIndexImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => MainRoute,
} as any)

const MainMapIndexRoute = MainMapIndexImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => MainRoute,
} as any)

const MainHrEditHrEditLazyRoute = MainHrEditHrEditLazyImport.update({
  id: '/hr-edit/$hr-edit',
  path: '/hr-edit/$hr-edit',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/hr-edit/$hr-edit.lazy').then((d) => d.Route),
)

const MainProjectIdRoute = MainProjectIdImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainPositionHrViewIdRoute = MainPositionHrViewIdImport.update({
  id: '/position-hr-view/$id',
  path: '/position-hr-view/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainPlansCheckoutRoute = MainPlansCheckoutImport.update({
  id: '/plans/checkout',
  path: '/plans/checkout',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeCreateRoute = MainOfficeCreateImport.update({
  id: '/office/create',
  path: '/office/create',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeIdRoute = MainOfficeIdImport.update({
  id: '/office/$id',
  path: '/office/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeEditIdRoute = MainOfficeEditIdImport.update({
  id: '/office-edit/$id',
  path: '/office-edit/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainHrViewIdRoute = MainHrViewIdImport.update({
  id: '/hr-view/$id',
  path: '/hr-view/$id',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_main/absent': {
      id: '/_main/absent'
      path: '/absent'
      fullPath: '/absent'
      preLoaderRoute: typeof MainAbsentImport
      parentRoute: typeof MainImport
    }
    '/_main/all-employees': {
      id: '/_main/all-employees'
      path: '/all-employees'
      fullPath: '/all-employees'
      preLoaderRoute: typeof MainAllEmployeesImport
      parentRoute: typeof MainImport
    }
    '/_main/arrivals': {
      id: '/_main/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof MainArrivalsImport
      parentRoute: typeof MainImport
    }
    '/_main/hr': {
      id: '/_main/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof MainHrImport
      parentRoute: typeof MainImport
    }
    '/_main/hr-create': {
      id: '/_main/hr-create'
      path: '/hr-create'
      fullPath: '/hr-create'
      preLoaderRoute: typeof MainHrCreateImport
      parentRoute: typeof MainImport
    }
    '/_main/landing': {
      id: '/_main/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof MainLandingImport
      parentRoute: typeof MainImport
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/hr-view/$id': {
      id: '/_main/hr-view/$id'
      path: '/hr-view/$id'
      fullPath: '/hr-view/$id'
      preLoaderRoute: typeof MainHrViewIdImport
      parentRoute: typeof MainImport
    }
    '/_main/office-edit/$id': {
      id: '/_main/office-edit/$id'
      path: '/office-edit/$id'
      fullPath: '/office-edit/$id'
      preLoaderRoute: typeof MainOfficeEditIdImport
      parentRoute: typeof MainImport
    }
    '/_main/office/$id': {
      id: '/_main/office/$id'
      path: '/office/$id'
      fullPath: '/office/$id'
      preLoaderRoute: typeof MainOfficeIdImport
      parentRoute: typeof MainImport
    }
    '/_main/office/create': {
      id: '/_main/office/create'
      path: '/office/create'
      fullPath: '/office/create'
      preLoaderRoute: typeof MainOfficeCreateImport
      parentRoute: typeof MainImport
    }
    '/_main/plans/checkout': {
      id: '/_main/plans/checkout'
      path: '/plans/checkout'
      fullPath: '/plans/checkout'
      preLoaderRoute: typeof MainPlansCheckoutImport
      parentRoute: typeof MainImport
    }
    '/_main/position-hr-view/$id': {
      id: '/_main/position-hr-view/$id'
      path: '/position-hr-view/$id'
      fullPath: '/position-hr-view/$id'
      preLoaderRoute: typeof MainPositionHrViewIdImport
      parentRoute: typeof MainImport
    }
    '/_main/project/$id': {
      id: '/_main/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof MainProjectIdImport
      parentRoute: typeof MainImport
    }
    '/_main/hr-edit/$hr-edit': {
      id: '/_main/hr-edit/$hr-edit'
      path: '/hr-edit/$hr-edit'
      fullPath: '/hr-edit/$hr-edit'
      preLoaderRoute: typeof MainHrEditHrEditLazyImport
      parentRoute: typeof MainImport
    }
    '/_main/map/': {
      id: '/_main/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MainMapIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/office/': {
      id: '/_main/office/'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof MainOfficeIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/plans/': {
      id: '/_main/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof MainPlansIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/project/': {
      id: '/_main/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof MainProjectIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/requests/': {
      id: '/_main/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof MainRequestsIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/roles/': {
      id: '/_main/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainRolesIndexImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainAbsentRoute: typeof MainAbsentRoute
  MainAllEmployeesRoute: typeof MainAllEmployeesRoute
  MainArrivalsRoute: typeof MainArrivalsRoute
  MainHrRoute: typeof MainHrRoute
  MainHrCreateRoute: typeof MainHrCreateRoute
  MainLandingRoute: typeof MainLandingRoute
  MainIndexRoute: typeof MainIndexRoute
  MainHrViewIdRoute: typeof MainHrViewIdRoute
  MainOfficeEditIdRoute: typeof MainOfficeEditIdRoute
  MainOfficeIdRoute: typeof MainOfficeIdRoute
  MainOfficeCreateRoute: typeof MainOfficeCreateRoute
  MainPlansCheckoutRoute: typeof MainPlansCheckoutRoute
  MainPositionHrViewIdRoute: typeof MainPositionHrViewIdRoute
  MainProjectIdRoute: typeof MainProjectIdRoute
  MainHrEditHrEditLazyRoute: typeof MainHrEditHrEditLazyRoute
  MainMapIndexRoute: typeof MainMapIndexRoute
  MainOfficeIndexRoute: typeof MainOfficeIndexRoute
  MainPlansIndexRoute: typeof MainPlansIndexRoute
  MainProjectIndexRoute: typeof MainProjectIndexRoute
  MainRequestsIndexRoute: typeof MainRequestsIndexRoute
  MainRolesIndexRoute: typeof MainRolesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAbsentRoute: MainAbsentRoute,
  MainAllEmployeesRoute: MainAllEmployeesRoute,
  MainArrivalsRoute: MainArrivalsRoute,
  MainHrRoute: MainHrRoute,
  MainHrCreateRoute: MainHrCreateRoute,
  MainLandingRoute: MainLandingRoute,
  MainIndexRoute: MainIndexRoute,
  MainHrViewIdRoute: MainHrViewIdRoute,
  MainOfficeEditIdRoute: MainOfficeEditIdRoute,
  MainOfficeIdRoute: MainOfficeIdRoute,
  MainOfficeCreateRoute: MainOfficeCreateRoute,
  MainPlansCheckoutRoute: MainPlansCheckoutRoute,
  MainPositionHrViewIdRoute: MainPositionHrViewIdRoute,
  MainProjectIdRoute: MainProjectIdRoute,
  MainHrEditHrEditLazyRoute: MainHrEditHrEditLazyRoute,
  MainMapIndexRoute: MainMapIndexRoute,
  MainOfficeIndexRoute: MainOfficeIndexRoute,
  MainPlansIndexRoute: MainPlansIndexRoute,
  MainProjectIndexRoute: MainProjectIndexRoute,
  MainRequestsIndexRoute: MainRequestsIndexRoute,
  MainRolesIndexRoute: MainRolesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/absent': typeof MainAbsentRoute
  '/all-employees': typeof MainAllEmployeesRoute
  '/arrivals': typeof MainArrivalsRoute
  '/hr': typeof MainHrRoute
  '/hr-create': typeof MainHrCreateRoute
  '/landing': typeof MainLandingRoute
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/hr-view/$id': typeof MainHrViewIdRoute
  '/office-edit/$id': typeof MainOfficeEditIdRoute
  '/office/$id': typeof MainOfficeIdRoute
  '/office/create': typeof MainOfficeCreateRoute
  '/plans/checkout': typeof MainPlansCheckoutRoute
  '/position-hr-view/$id': typeof MainPositionHrViewIdRoute
  '/project/$id': typeof MainProjectIdRoute
  '/hr-edit/$hr-edit': typeof MainHrEditHrEditLazyRoute
  '/map': typeof MainMapIndexRoute
  '/office': typeof MainOfficeIndexRoute
  '/plans': typeof MainPlansIndexRoute
  '/project': typeof MainProjectIndexRoute
  '/requests': typeof MainRequestsIndexRoute
  '/roles': typeof MainRolesIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/absent': typeof MainAbsentRoute
  '/all-employees': typeof MainAllEmployeesRoute
  '/arrivals': typeof MainArrivalsRoute
  '/hr': typeof MainHrRoute
  '/hr-create': typeof MainHrCreateRoute
  '/landing': typeof MainLandingRoute
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/hr-view/$id': typeof MainHrViewIdRoute
  '/office-edit/$id': typeof MainOfficeEditIdRoute
  '/office/$id': typeof MainOfficeIdRoute
  '/office/create': typeof MainOfficeCreateRoute
  '/plans/checkout': typeof MainPlansCheckoutRoute
  '/position-hr-view/$id': typeof MainPositionHrViewIdRoute
  '/project/$id': typeof MainProjectIdRoute
  '/hr-edit/$hr-edit': typeof MainHrEditHrEditLazyRoute
  '/map': typeof MainMapIndexRoute
  '/office': typeof MainOfficeIndexRoute
  '/plans': typeof MainPlansIndexRoute
  '/project': typeof MainProjectIndexRoute
  '/requests': typeof MainRequestsIndexRoute
  '/roles': typeof MainRolesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_main/absent': typeof MainAbsentRoute
  '/_main/all-employees': typeof MainAllEmployeesRoute
  '/_main/arrivals': typeof MainArrivalsRoute
  '/_main/hr': typeof MainHrRoute
  '/_main/hr-create': typeof MainHrCreateRoute
  '/_main/landing': typeof MainLandingRoute
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/hr-view/$id': typeof MainHrViewIdRoute
  '/_main/office-edit/$id': typeof MainOfficeEditIdRoute
  '/_main/office/$id': typeof MainOfficeIdRoute
  '/_main/office/create': typeof MainOfficeCreateRoute
  '/_main/plans/checkout': typeof MainPlansCheckoutRoute
  '/_main/position-hr-view/$id': typeof MainPositionHrViewIdRoute
  '/_main/project/$id': typeof MainProjectIdRoute
  '/_main/hr-edit/$hr-edit': typeof MainHrEditHrEditLazyRoute
  '/_main/map/': typeof MainMapIndexRoute
  '/_main/office/': typeof MainOfficeIndexRoute
  '/_main/plans/': typeof MainPlansIndexRoute
  '/_main/project/': typeof MainProjectIndexRoute
  '/_main/requests/': typeof MainRequestsIndexRoute
  '/_main/roles/': typeof MainRolesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/absent'
    | '/all-employees'
    | '/arrivals'
    | '/hr'
    | '/hr-create'
    | '/landing'
    | '/auth'
    | '/'
    | '/hr-view/$id'
    | '/office-edit/$id'
    | '/office/$id'
    | '/office/create'
    | '/plans/checkout'
    | '/position-hr-view/$id'
    | '/project/$id'
    | '/hr-edit/$hr-edit'
    | '/map'
    | '/office'
    | '/plans'
    | '/project'
    | '/requests'
    | '/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/absent'
    | '/all-employees'
    | '/arrivals'
    | '/hr'
    | '/hr-create'
    | '/landing'
    | '/auth'
    | '/'
    | '/hr-view/$id'
    | '/office-edit/$id'
    | '/office/$id'
    | '/office/create'
    | '/plans/checkout'
    | '/position-hr-view/$id'
    | '/project/$id'
    | '/hr-edit/$hr-edit'
    | '/map'
    | '/office'
    | '/plans'
    | '/project'
    | '/requests'
    | '/roles'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_main/absent'
    | '/_main/all-employees'
    | '/_main/arrivals'
    | '/_main/hr'
    | '/_main/hr-create'
    | '/_main/landing'
    | '/_auth/auth'
    | '/_main/'
    | '/_main/hr-view/$id'
    | '/_main/office-edit/$id'
    | '/_main/office/$id'
    | '/_main/office/create'
    | '/_main/plans/checkout'
    | '/_main/position-hr-view/$id'
    | '/_main/project/$id'
    | '/_main/hr-edit/$hr-edit'
    | '/_main/map/'
    | '/_main/office/'
    | '/_main/plans/'
    | '/_main/project/'
    | '/_main/requests/'
    | '/_main/roles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/absent",
        "/_main/all-employees",
        "/_main/arrivals",
        "/_main/hr",
        "/_main/hr-create",
        "/_main/landing",
        "/_main/",
        "/_main/hr-view/$id",
        "/_main/office-edit/$id",
        "/_main/office/$id",
        "/_main/office/create",
        "/_main/plans/checkout",
        "/_main/position-hr-view/$id",
        "/_main/project/$id",
        "/_main/hr-edit/$hr-edit",
        "/_main/map/",
        "/_main/office/",
        "/_main/plans/",
        "/_main/project/",
        "/_main/requests/",
        "/_main/roles/"
      ]
    },
    "/_main/absent": {
      "filePath": "_main/absent.tsx",
      "parent": "/_main"
    },
    "/_main/all-employees": {
      "filePath": "_main/all-employees.tsx",
      "parent": "/_main"
    },
    "/_main/arrivals": {
      "filePath": "_main/arrivals.tsx",
      "parent": "/_main"
    },
    "/_main/hr": {
      "filePath": "_main/hr.tsx",
      "parent": "/_main"
    },
    "/_main/hr-create": {
      "filePath": "_main/hr-create.tsx",
      "parent": "/_main"
    },
    "/_main/landing": {
      "filePath": "_main/landing.tsx",
      "parent": "/_main"
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/hr-view/$id": {
      "filePath": "_main/hr-view/$id.tsx",
      "parent": "/_main"
    },
    "/_main/office-edit/$id": {
      "filePath": "_main/office-edit/$id.tsx",
      "parent": "/_main"
    },
    "/_main/office/$id": {
      "filePath": "_main/office/$id.tsx",
      "parent": "/_main"
    },
    "/_main/office/create": {
      "filePath": "_main/office/create.tsx",
      "parent": "/_main"
    },
    "/_main/plans/checkout": {
      "filePath": "_main/plans/checkout.tsx",
      "parent": "/_main"
    },
    "/_main/position-hr-view/$id": {
      "filePath": "_main/position-hr-view/$id.tsx",
      "parent": "/_main"
    },
    "/_main/project/$id": {
      "filePath": "_main/project/$id.tsx",
      "parent": "/_main"
    },
    "/_main/hr-edit/$hr-edit": {
      "filePath": "_main/hr-edit/$hr-edit.lazy.tsx",
      "parent": "/_main"
    },
    "/_main/map/": {
      "filePath": "_main/map/index.tsx",
      "parent": "/_main"
    },
    "/_main/office/": {
      "filePath": "_main/office/index.tsx",
      "parent": "/_main"
    },
    "/_main/plans/": {
      "filePath": "_main/plans/index.tsx",
      "parent": "/_main"
    },
    "/_main/project/": {
      "filePath": "_main/project/index.tsx",
      "parent": "/_main"
    },
    "/_main/requests/": {
      "filePath": "_main/requests/index.tsx",
      "parent": "/_main"
    },
    "/_main/roles/": {
      "filePath": "_main/roles/index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
