/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainImport } from './routes/_main'
import { Route as AuthImport } from './routes/_auth'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainRolesIndexImport } from './routes/_main/roles/index'
import { Route as MainMapIndexImport } from './routes/_main/map/index'
import { Route as MainOfficeCreateImport } from './routes/_main/office/create'
import { Route as MainOfficeIdImport } from './routes/_main/office/$id'
import { Route as MainOfficeEditIdImport } from './routes/_main/office-edit/$id'

// Create Virtual Routes

const AuthAuthLazyImport = createFileRoute('/_auth/auth')()

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)

const AuthAuthLazyRoute = AuthAuthLazyImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/auth.lazy').then((d) => d.Route))

const MainRolesIndexRoute = MainRolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => MainRoute,
} as any)

const MainMapIndexRoute = MainMapIndexImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeCreateRoute = MainOfficeCreateImport.update({
  id: '/office/create',
  path: '/office/create',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeIdRoute = MainOfficeIdImport.update({
  id: '/office/$id',
  path: '/office/$id',
  getParentRoute: () => MainRoute,
} as any)

const MainOfficeEditIdRoute = MainOfficeEditIdImport.update({
  id: '/office-edit/$id',
  path: '/office-edit/$id',
  getParentRoute: () => MainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLazyImport
      parentRoute: typeof AuthImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/office-edit/$id': {
      id: '/_main/office-edit/$id'
      path: '/office-edit/$id'
      fullPath: '/office-edit/$id'
      preLoaderRoute: typeof MainOfficeEditIdImport
      parentRoute: typeof MainImport
    }
    '/_main/office/$id': {
      id: '/_main/office/$id'
      path: '/office/$id'
      fullPath: '/office/$id'
      preLoaderRoute: typeof MainOfficeIdImport
      parentRoute: typeof MainImport
    }
    '/_main/office/create': {
      id: '/_main/office/create'
      path: '/office/create'
      fullPath: '/office/create'
      preLoaderRoute: typeof MainOfficeCreateImport
      parentRoute: typeof MainImport
    }
    '/_main/map/': {
      id: '/_main/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MainMapIndexImport
      parentRoute: typeof MainImport
    }
    '/_main/roles/': {
      id: '/_main/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof MainRolesIndexImport
      parentRoute: typeof MainImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAuthLazyRoute: typeof AuthAuthLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLazyRoute: AuthAuthLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainOfficeEditIdRoute: typeof MainOfficeEditIdRoute
  MainOfficeIdRoute: typeof MainOfficeIdRoute
  MainOfficeCreateRoute: typeof MainOfficeCreateRoute
  MainMapIndexRoute: typeof MainMapIndexRoute
  MainRolesIndexRoute: typeof MainRolesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainOfficeEditIdRoute: MainOfficeEditIdRoute,
  MainOfficeIdRoute: MainOfficeIdRoute,
  MainOfficeCreateRoute: MainOfficeCreateRoute,
  MainMapIndexRoute: MainMapIndexRoute,
  MainRolesIndexRoute: MainRolesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof MainRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/office-edit/$id': typeof MainOfficeEditIdRoute
  '/office/$id': typeof MainOfficeIdRoute
  '/office/create': typeof MainOfficeCreateRoute
  '/map': typeof MainMapIndexRoute
  '/roles': typeof MainRolesIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/auth': typeof AuthAuthLazyRoute
  '/': typeof MainIndexRoute
  '/office-edit/$id': typeof MainOfficeEditIdRoute
  '/office/$id': typeof MainOfficeIdRoute
  '/office/create': typeof MainOfficeCreateRoute
  '/map': typeof MainMapIndexRoute
  '/roles': typeof MainRolesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/auth': typeof AuthAuthLazyRoute
  '/_main/': typeof MainIndexRoute
  '/_main/office-edit/$id': typeof MainOfficeEditIdRoute
  '/_main/office/$id': typeof MainOfficeIdRoute
  '/_main/office/create': typeof MainOfficeCreateRoute
  '/_main/map/': typeof MainMapIndexRoute
  '/_main/roles/': typeof MainRolesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/auth' | '/' | '/map' | '/roles'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/auth' | '/' | '/map' | '/roles'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_main/'
    | '/_main/office-edit/$id'
    | '/_main/office/$id'
    | '/_main/office/create'
    | '/_main/map/'
    | '/_main/roles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_main"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auth"
      ]
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/",
        "/_main/map/",
        "/_main/roles/"
      ]
    },
    "/_auth/auth": {
      "filePath": "_auth/auth.lazy.tsx",
      "parent": "/_auth"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/office-edit/$id": {
      "filePath": "_main/office-edit/$id.tsx",
      "parent": "/_main"
    },
    "/_main/office/$id": {
      "filePath": "_main/office/$id.tsx",
      "parent": "/_main"
    },
    "/_main/office/create": {
      "filePath": "_main/office/create.tsx",
      "parent": "/_main"
    },
    "/_main/map/": {
      "filePath": "_main/map/index.tsx",
      "parent": "/_main"
    },
    "/_main/roles/": {
      "filePath": "_main/roles/index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
